modules:
  stn:
    img_h: 96
    img_w: 2304 # 96 * 24
    num_fiducial: 20

  bilstm:
    hidden_size: 256

  beamsearch:
    emission_thresh: 0.01
    beam_size: 10

  lmfusion:
    weight: 0.01

rare:
  input_channel: 3
  output_channel: 512
  num_class: 193
  label_max_length: 45

device: cuda
