[
  ["EGIR", "pa", " ", "ti", "an", "zi"], # OK
  [
    "nu",
    "uš",
    "ša",
    "an",
    " ",
    "A",
    "NA",
    " ",
    "NINDA",
    "GUR",
    "RA",
    " ",
    "ŠE",
    "ER",
  ], # OK
  [
    "pé",
    "ra",
    "an",
    " ",
    "kat",
    "ta",
    "ma",
    " ",
    "ki",
    "ne",
    " ",
    "i",
    "ia",
    "mi",
  ], # OK
  ["NINDA", "šar", "li", "in", "na", " ", "te", "eḫ", "ḫi"], # OK
  ["a", "da", "an", "zi", " ", "a", "ku", "wa", "an", "zi"], # OK
  ["MAḪ", "aš", " ", "LUGAL", "i", " ", "MUNUS", "LUGAL", "i"], # OK
  [
    "ap",
    "pa",
    "an",
    "zi",
    " ",
    "pa",
    "ri",
    "li",
    "ia",
    "aš",
    "ša",
    " ",
    "MUŠEN",
    "ḪI",
    "A",
  ], # OK
  [
    "nu",
    "za",
    " ",
    "wa",
    "ar",
    "ap",
    "zi",
    " ",
    "nam",
    "ma",
    "za",
    "a",
    "pa",
    "a",
    "aš",
  ], # OK
  [
    "9",
    "NA@4",
    "pa",
    "aš",
    "ši",
    "la",
    "aš",
    " ",
    "A",
    "ŠÀ",
    " ",
    "te",
    "ri",
    "ip",
    "pí",
    "aš",
  ], # OK
]
