dataset:
  signs: "dataset/target_hittite_cuneiform_signs.json"
  train:
    image: "dataset/images"
    label: "dataset/annotations"
    first_index: 0
    last_index: 700
  valid:
    image: "dataset/images"
    label: "dataset/annotations"
    first_index: 701
    last_index: 850

dump:
  weight: output/weight

epoch: 30
device: cuda
batch_size: 5
log_interval: 300
weight: "output/weight/last.pth"
