dataset:
  signs: "config/target_hittite_cuneiform_signs.json"
  train:
    image: "/storage/images"
    label: "/storage/annotations"
    first_index: 0
    last_index: 900999
  # valid:
  #   image: "dataset/images"
  #   label: "dataset/annotations"
  #   first_index: 901000
  #   last_index: 909999
  valid:
    image: "/storage/valid"

dump:
  weight: output/weight
  mlflow: "./mlruns"

epoch: 999
device: cuda
batch_size: 32
log_interval: 500
learning_rate: 0.001
weight_decay: 0.000001
weight: 
